//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesdeVentas
    {
        public int idventas { get; set; }
        public int idproducto { get; set; }
        public decimal preciounidad { get; set; }
        public int cantidad { get; set; }
    
        public virtual Ventas Ventas { get; set; }
        public virtual productos productos { get; set; }
    }
}
