//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public Empleados()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdEmpleado { get; set; }
        public string Apellidos { get; set; }
        public string Nombre { get; set; }
        public string cargo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaContratacion { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string TelDomicilio { get; set; }
        public Nullable<decimal> sueldoBasico { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
