//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public productos()
        {
            this.detallesdeVentas = new HashSet<detallesdeVentas>();
        }
    
        public int idproducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<decimal> precioUnidad { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual ICollection<detallesdeVentas> detallesdeVentas { get; set; }
    }
}
