//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string id { get; set; }
        public string pwd { get; set; }
        public string nombre { get; set; }
        public Nullable<int> intentos { get; set; }
        public Nullable<bool> estado { get; set; }
        public string tipoUsuario { get; set; }
    }
}
