//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMiniMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.detallesdeVentas = new HashSet<detallesdeVentas>();
        }
    
        public int IdVentas { get; set; }
        public string IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual ICollection<detallesdeVentas> detallesdeVentas { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
